const PROVIDERS = {
  // ── OAuth2 Platforms ──────────────────────────────

  google: {
    id: 'google',
    name: 'Google',
    description: 'Google Ads, Analytics & YouTube',
    category: 'ads',
    authType: 'oauth2',
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    scopes: [
      'https://www.googleapis.com/auth/adwords',
      'https://www.googleapis.com/auth/analytics.readonly',
      'https://www.googleapis.com/auth/youtube.readonly',
      'openid', 'email', 'profile',
    ],
    envClientId: 'GOOGLE_CLIENT_ID',
    envClientSecret: 'GOOGLE_CLIENT_SECRET',
    extraAuthParams: { access_type: 'offline', prompt: 'consent' },
    profileUrl: 'https://www.googleapis.com/oauth2/v2/userinfo',
  },

  meta: {
    id: 'meta',
    name: 'Meta',
    description: 'Facebook & Instagram Ads',
    category: 'ads',
    authType: 'oauth2',
    authUrl: 'https://www.facebook.com/v19.0/dialog/oauth',
    tokenUrl: 'https://graph.facebook.com/v19.0/oauth/access_token',
    scopes: ['ads_management', 'ads_read', 'business_management'],
    envClientId: 'META_CLIENT_ID',
    envClientSecret: 'META_CLIENT_SECRET',
    profileUrl: 'https://graph.facebook.com/me?fields=name,email',
  },

  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    description: 'TikTok Ads Manager',
    category: 'ads',
    authType: 'oauth2',
    authUrl: 'https://business-api.tiktok.com/portal/auth',
    tokenUrl: 'https://business-api.tiktok.com/open_api/v1.3/oauth2/access_token/',
    scopes: [],
    envClientId: 'TIKTOK_CLIENT_ID',
    envClientSecret: 'TIKTOK_CLIENT_SECRET',
    authParamMapping: { client_id: 'app_id' },
  },

  shopify: {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform',
    category: 'ecommerce',
    authType: 'oauth2',
    authUrlTemplate: 'https://{shop}.myshopify.com/admin/oauth/authorize',
    tokenUrlTemplate: 'https://{shop}.myshopify.com/admin/oauth/access_token',
    scopes: ['read_products', 'read_orders', 'read_analytics'],
    envClientId: 'SHOPIFY_CLIENT_ID',
    envClientSecret: 'SHOPIFY_CLIENT_SECRET',
    requiresShop: true,
  },

  stripe: {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing',
    category: 'payments',
    authType: 'oauth2',
    authUrl: 'https://connect.stripe.com/oauth/authorize',
    tokenUrl: 'https://connect.stripe.com/oauth/token',
    scopes: ['read_write'],
    envClientId: 'STRIPE_CLIENT_ID',
    envClientSecret: 'STRIPE_CLIENT_SECRET',
    extraAuthParams: { response_type: 'code' },
  },

  mailchimp: {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing and automation',
    category: 'email',
    authType: 'oauth2',
    authUrl: 'https://login.mailchimp.com/oauth2/authorize',
    tokenUrl: 'https://login.mailchimp.com/oauth2/token',
    scopes: [],
    envClientId: 'MAILCHIMP_CLIENT_ID',
    envClientSecret: 'MAILCHIMP_CLIENT_SECRET',
  },

  hubspot: {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM and marketing automation',
    category: 'crm',
    authType: 'oauth2',
    authUrl: 'https://app.hubspot.com/oauth/authorize',
    tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
    scopes: ['crm.objects.contacts.read', 'crm.objects.deals.read'],
    envClientId: 'HUBSPOT_CLIENT_ID',
    envClientSecret: 'HUBSPOT_CLIENT_SECRET',
  },

  slack: {
    id: 'slack',
    name: 'Slack',
    description: 'Team messaging and notifications',
    category: 'messaging',
    authType: 'oauth2',
    authUrl: 'https://slack.com/oauth/v2/authorize',
    tokenUrl: 'https://slack.com/api/oauth.v2.access',
    scopes: ['chat:write', 'channels:read'],
    envClientId: 'SLACK_CLIENT_ID',
    envClientSecret: 'SLACK_CLIENT_SECRET',
  },

  amazon: {
    id: 'amazon',
    name: 'Amazon',
    description: 'Seller Central / SP-API',
    category: 'ecommerce',
    authType: 'oauth2',
    authUrl: 'https://sellercentral.amazon.com/apps/authorize/consent',
    tokenUrl: 'https://api.amazon.com/auth/o2/token',
    scopes: [],
    envClientId: 'AMAZON_CLIENT_ID',
    envClientSecret: 'AMAZON_CLIENT_SECRET',
  },

  notion: {
    id: 'notion',
    name: 'Notion',
    description: 'Workspace and project management',
    category: 'productivity',
    authType: 'oauth2',
    authUrl: 'https://api.notion.com/v1/oauth/authorize',
    tokenUrl: 'https://api.notion.com/v1/oauth/token',
    scopes: [],
    envClientId: 'NOTION_CLIENT_ID',
    envClientSecret: 'NOTION_CLIENT_SECRET',
    tokenAuthMethod: 'basic',
  },

  airtable: {
    id: 'airtable',
    name: 'Airtable',
    description: 'Flexible database and project management',
    category: 'productivity',
    authType: 'oauth2',
    authUrl: 'https://airtable.com/oauth2/v1/authorize',
    tokenUrl: 'https://airtable.com/oauth2/v1/token',
    scopes: ['data.records:read', 'data.records:write', 'schema.bases:read'],
    envClientId: 'AIRTABLE_CLIENT_ID',
    envClientSecret: 'AIRTABLE_CLIENT_SECRET',
    usePKCE: true,
  },

  pinterest: {
    id: 'pinterest',
    name: 'Pinterest Ads',
    description: 'Visual discovery and advertising',
    category: 'ads',
    authType: 'oauth2',
    authUrl: 'https://www.pinterest.com/oauth/',
    tokenUrl: 'https://api.pinterest.com/v5/oauth/token',
    scopes: ['ads:read', 'ads:write'],
    envClientId: 'PINTEREST_CLIENT_ID',
    envClientSecret: 'PINTEREST_CLIENT_SECRET',
  },

  snapchat: {
    id: 'snapchat',
    name: 'Snapchat Ads',
    description: 'Social advertising for younger audiences',
    category: 'ads',
    authType: 'oauth2',
    authUrl: 'https://accounts.snapchat.com/login/oauth2/authorize',
    tokenUrl: 'https://accounts.snapchat.com/login/oauth2/access_token',
    scopes: ['snapchat-marketing-api'],
    envClientId: 'SNAPCHAT_CLIENT_ID',
    envClientSecret: 'SNAPCHAT_CLIENT_SECRET',
  },

  intercom: {
    id: 'intercom',
    name: 'Intercom',
    description: 'Customer messaging and support',
    category: 'messaging',
    authType: 'oauth2',
    authUrl: 'https://app.intercom.com/oauth',
    tokenUrl: 'https://api.intercom.io/auth/eagle/token',
    scopes: [],
    envClientId: 'INTERCOM_CLIENT_ID',
    envClientSecret: 'INTERCOM_CLIENT_SECRET',
  },

  bigcommerce: {
    id: 'bigcommerce',
    name: 'BigCommerce',
    description: 'E-commerce platform for growing brands',
    category: 'ecommerce',
    authType: 'oauth2',
    authUrl: 'https://login.bigcommerce.com/oauth2/authorize',
    tokenUrl: 'https://login.bigcommerce.com/oauth2/token',
    scopes: ['store_v2_products_read_only', 'store_v2_orders_read_only'],
    envClientId: 'BIGCOMMERCE_CLIENT_ID',
    envClientSecret: 'BIGCOMMERCE_CLIENT_SECRET',
  },

  // ── API Key Platforms ─────────────────────────────

  klaviyo: {
    id: 'klaviyo',
    name: 'Klaviyo',
    description: 'Email and SMS marketing',
    category: 'email',
    authType: 'api_key',
    credentials: [
      { key: 'api_key', label: 'Private API Key', type: 'password', required: true },
    ],
    testUrl: 'https://a.klaviyo.com/api/accounts/',
    testHeaders: (creds) => ({ 'Authorization': `Klaviyo-API-Key ${creds.api_key}`, 'revision': '2024-02-15' }),
  },

  segment: {
    id: 'segment',
    name: 'Segment',
    description: 'Customer data platform',
    category: 'data',
    authType: 'api_key',
    credentials: [
      { key: 'write_key', label: 'Write Key', type: 'password', required: true },
    ],
  },

  mixpanel: {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product analytics and tracking',
    category: 'analytics',
    authType: 'api_key',
    credentials: [
      { key: 'project_token', label: 'Project Token', type: 'text', required: true },
      { key: 'api_secret', label: 'API Secret', type: 'password', required: true },
    ],
  },

  twilio: {
    id: 'twilio',
    name: 'Twilio',
    description: 'SMS and communication APIs',
    category: 'messaging',
    authType: 'api_key',
    credentials: [
      { key: 'account_sid', label: 'Account SID', type: 'text', required: true },
      { key: 'auth_token', label: 'Auth Token', type: 'password', required: true },
    ],
  },

  zapier: {
    id: 'zapier',
    name: 'Zapier',
    description: 'Workflow automation via webhooks',
    category: 'automation',
    authType: 'api_key',
    credentials: [
      { key: 'webhook_url', label: 'Webhook URL', type: 'url', required: true },
    ],
  },
};

module.exports = { PROVIDERS };
